#!/bin/bash

# Auto-Build Environment Setup — VISE OS Bot
# Generated by Planner Agent
# Date: 2026-02-26

set -e

echo "========================================"
echo "VISE OS — Development Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# STEP 1: Verify Python 3.11+
# ============================================

echo ""
echo "Checking Python version..."
PYTHON_VERSION=$(python3 --version 2>&1 | awk '{print $2}')
PYTHON_MAJOR=$(echo "$PYTHON_VERSION" | cut -d. -f1)
PYTHON_MINOR=$(echo "$PYTHON_VERSION" | cut -d. -f2)

if [ "$PYTHON_MAJOR" -lt 3 ] || ([ "$PYTHON_MAJOR" -eq 3 ] && [ "$PYTHON_MINOR" -lt 11 ]); then
    echo -e "${RED}Python 3.11+ required. Found: $PYTHON_VERSION${NC}"
    exit 1
fi
echo -e "${GREEN}Python $PYTHON_VERSION OK${NC}"

# ============================================
# STEP 2: Install Python Dependencies
# ============================================

echo ""
echo "Installing Python dependencies..."
pip install -U camoufox[geoip] python-dotenv imap-tools capsolver 2>&1 | tail -3
echo -e "${GREEN}Dependencies installed${NC}"

# ============================================
# STEP 3: Download Camoufox Browser Binary
# ============================================

echo ""
echo "Downloading Camoufox browser binary..."
camoufox fetch 2>&1 | tail -3
echo -e "${GREEN}Camoufox browser ready${NC}"

# ============================================
# STEP 4: Linux-specific — Install Xvfb
# ============================================

if [ "$(uname)" = "Linux" ]; then
    echo ""
    echo -e "${YELLOW}Linux detected — checking Xvfb...${NC}"
    if ! command -v Xvfb &> /dev/null; then
        echo "Installing Xvfb and system libraries..."
        sudo apt install -y xvfb libgtk-3-0 libx11-xcb1 libasound2 2>&1 | tail -3
        echo -e "${GREEN}Xvfb installed${NC}"
    else
        echo -e "${GREEN}Xvfb already installed${NC}"
    fi
fi

# ============================================
# STEP 5: Verify .env exists
# ============================================

echo ""
if [ ! -f ".env" ]; then
    if [ -f ".env.example" ]; then
        echo -e "${YELLOW}No .env found. Copying from .env.example...${NC}"
        cp .env.example .env
        echo -e "${YELLOW}Please edit .env with real credentials before running the bot!${NC}"
    else
        echo -e "${RED}No .env or .env.example found!${NC}"
        exit 1
    fi
else
    echo -e "${GREEN}.env file exists${NC}"
fi

# ============================================
# STEP 6: Create debug directories
# ============================================

echo ""
echo "Ensuring debug directories exist..."
mkdir -p debug/screenshots debug/har debug/logs
echo -e "${GREEN}Debug directories ready${NC}"

# ============================================
# STEP 7: Verify imports
# ============================================

echo ""
echo "Verifying module imports..."
python3 -c "
from dotenv import load_dotenv
load_dotenv()
try:
    from src.platform_config import platform_ayarlari_al
    print('  platform_config ... OK')
except ImportError as e:
    print(f'  platform_config ... SKIP ({e})')
try:
    from src.country_manager import UlkeYonetici
    print('  country_manager ... OK')
except ImportError as e:
    print(f'  country_manager ... SKIP ({e})')
try:
    from src.utils import log
    print('  utils ... OK')
except ImportError as e:
    print(f'  utils ... SKIP ({e})')
try:
    from src.browser import tarayici_baslat
    print('  browser ... OK')
except ImportError as e:
    print(f'  browser ... SKIP ({e})')
" 2>&1

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Usage:"
echo "  python main.py register --country aut   # Register on Austria (MVP)"
echo "  python main.py login --country aut      # Login on Austria"
echo "  python main.py test --country aut       # Full test (register + login)"
echo ""
echo "Run tests:"
echo "  python -m pytest tests/ -v              # Unit tests"
echo ""
echo -e "${YELLOW}Remember: Edit .env with real credentials before running!${NC}"
echo ""
